# Auto generated configuration file
# using: 
# Revision: 1.222.2.6 
# Source: /cvs_server/repositories/CMSSW/CMSSW/Configuration/PyReleaseValidation/python/ConfigBuilder.py,v 
# with command line options: reconstruction_387_ppmc -s RAW2DIGI,L1Reco,RECO --datatier GEN-SIM-RECO --eventcontent RECOSIM --customise Configuration/GlobalRuns/reco_TLR_38X.customisePPMC --conditions MC_38Y_V14::All --no_exec --filein file:GenHLT.root
import FWCore.ParameterSet.Config as cms

process = cms.Process('RECO')

# import of standard configurations
process.load('Configuration.StandardSequences.Services_cff')
process.load('SimGeneral.HepPDTESSource.pythiapdt_cfi')
process.load('FWCore.MessageService.MessageLogger_cfi')
process.load('Configuration.StandardSequences.MixingNoPileUp_cff')
process.load('Configuration.StandardSequences.GeometryDB_cff')
process.load('Configuration.StandardSequences.MagneticField_38T_cff')
process.load('Configuration.StandardSequences.RawToDigi_cff')
process.load('Configuration.StandardSequences.L1Reco_cff')
process.load('Configuration.StandardSequences.Reconstruction_cff')
process.load('Configuration.StandardSequences.EndOfProcess_cff')
process.load('Configuration.StandardSequences.FrontierConditions_GlobalTag_cff')
process.load('Configuration.EventContent.EventContent_cff')

process.configurationMetadata = cms.untracked.PSet(
    version = cms.untracked.string('$Revision: 1.222.2.6 $'),
    annotation = cms.untracked.string('reconstruction_387_ppmc nevts:1'),
    name = cms.untracked.string('PyReleaseValidation')
)
process.maxEvents = cms.untracked.PSet(
    input = cms.untracked.int32(-1)
)
process.options = cms.untracked.PSet(

)

fnames1 = ['file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_1000_1_VvB.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_100_1_P1M.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_101_1_MxX.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_10_1_9W4.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_102_1_XEO.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_103_1_Ptr.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_104_1_xh2.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_105_1_3zS.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_106_1_3Wu.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_107_1_WF1.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_108_1_QR7.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_109_2_wgT.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_110_1_i7n.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_111_1_UiY.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_112_1_e1P.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_11_2_Dw4.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_113_1_nNU.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_114_1_twz.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_115_1_Q4X.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_116_1_8b9.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_117_1_1tR.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_118_1_Mbo.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_119_1_nTp.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_1_1_Mh7.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_120_1_YNJ.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_121_1_T6N.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_12_1_EJB.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_122_1_0AU.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_123_1_w1d.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_124_1_0O1.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_125_1_sET.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_126_1_vj4.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_127_1_gbF.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_128_1_RaF.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_129_2_531.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_130_1_P3w.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_131_1_cW8.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_13_1_D56.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_132_1_erB.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_133_1_spT.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_134_1_ICt.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_135_1_6zj.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_136_1_6rJ.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_137_1_Oyi.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_138_2_Bxd.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_139_2_rXu.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_140_2_CGm.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_141_1_B7y.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_14_1_OdH.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_142_1_zoL.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_143_1_8P8.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_144_1_Ie4.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_145_1_95u.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_146_1_K0G.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_147_1_lZd.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_148_1_umn.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_149_1_o5W.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_150_1_tV4.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_151_2_tRS.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_15_1_w4f.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_152_1_Hnp.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_153_1_xll.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_154_2_LKA.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_155_1_J0h.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_156_1_B9I.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_157_1_Wyq.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_158_1_lX5.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_159_1_7w4.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_160_3_rEy.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_161_1_7DM.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_16_1_xEE.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_162_1_q7c.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_163_1_Kgw.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_164_1_yfB.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_165_1_CVl.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_166_1_O56.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_167_1_826.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_168_1_Aqe.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_169_1_g70.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_170_1_SQ5.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_171_1_mep.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_17_1_al8.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_172_1_uWI.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_173_1_lZD.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_174_1_4s5.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_175_1_pxi.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_176_1_jzc.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_177_2_Gs0.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_178_1_Qmo.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_179_1_Mq0.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_180_1_vkL.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_181_2_Nnb.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_182_1_AOB.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_18_2_AKB.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_183_1_lgq.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_184_1_kll.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_185_1_wls.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_186_1_6tM.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_187_1_wrW.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_188_1_i0D.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_189_1_zt6.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_190_1_HVr.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_191_1_F24.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_19_1_wXJ.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_192_1_y1N.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_193_1_A7A.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_194_2_Y3j.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_195_1_zjW.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_196_2_FyI.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_197_1_WLn.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_198_1_Omr.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_199_1_ERy.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_200_1_C0l.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_201_2_gb4.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_20_1_a9r.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_202_1_gEZ.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_203_1_pkb.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_204_1_1Zh.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_205_1_8qX.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_206_1_RFe.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_207_1_st7.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_208_1_rqA.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_209_1_KoN.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_210_1_oL7.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_211_2_zMy.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_21_1_Btd.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_212_1_qiP.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_213_1_eTk.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_214_1_dbK.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_215_1_JAX.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_216_1_ShO.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_217_1_1tR.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_218_1_9xM.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_219_1_BrU.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_2_1_IFs.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_220_1_KA4.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_221_1_aXx.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_221_2_enQ.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_22_1_dHf.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_222_1_yNK.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_223_1_Fhw.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_224_1_Bvm.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_225_1_Xa2.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_226_1_87j.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_226_2_MCI.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_227_2_fe7.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_228_1_UJ2.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_229_1_cc1.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_230_1_4fG.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_230_2_gG1.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_231_1_xtz.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_23_1_PdV.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_232_1_4dR.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_233_1_VVe.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_234_1_EfL.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_235_1_uYi.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_236_2_iwc.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_237_1_e0G.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_238_1_P3i.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_239_1_TP7.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_240_1_c0T.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_240_2_Fqz.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_241_1_nLd.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_24_1_Gdg.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_242_1_BZJ.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_243_2_qsh.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_244_2_MXd.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_245_1_mGk.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_246_2_dRR.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_247_1_BoL.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_248_1_sDk.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_249_1_i5y.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_250_1_HCq.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_251_1_7QA.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_25_1_GQ5.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_252_2_NJ5.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_253_1_ej4.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_254_1_eEV.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_255_1_3Wt.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_256_1_Oel.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_257_1_aJe.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_258_1_8ER.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_259_1_DWx.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_260_1_YST.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_261_1_dtK.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_262_1_5QY.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_26_2_RQV.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_264_1_XBA.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_265_1_yda.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_266_2_Ugr.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_267_1_tiH.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_268_1_sU0.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_269_1_5Kn.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_270_2_Rx0.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_271_1_8bP.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_272_1_yR4.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_27_2_RyA.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_273_1_GDZ.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_274_1_zOK.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_275_1_uxv.root',
]
fnames2 = ['file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_276_1_bA8.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_277_1_gGW.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_278_1_kVr.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_279_1_2RY.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_280_1_cS5.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_281_1_Biv.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_28_1_riM.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_282_1_5LJ.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_283_1_fYG.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_284_1_OwK.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_285_1_MsK.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_286_2_9Xg.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_287_1_nRn.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_288_1_xT3.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_289_1_3xw.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_290_1_rFW.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_291_1_ohN.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_291_2_r1g.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_292_1_soJ.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_293_1_2US.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_294_1_J3S.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_295_1_86E.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_296_1_z9e.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_297_1_P6e.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_298_1_37P.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_299_1_ZVI.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_300_1_eNh.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_301_1_tO9.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_30_1_xjb.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_302_1_Gx6.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_302_2_hUa.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_303_1_FKb.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_304_1_dyr.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_305_1_Tlp.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_305_2_czm.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_306_1_TcQ.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_307_1_VoX.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_308_2_mYO.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_309_1_ck5.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_310_1_ikL.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_311_1_fVP.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_311_2_mRn.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_31_1_kGV.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_312_1_zY8.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_313_1_9hm.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_314_1_TdK.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_315_1_iEO.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_316_2_ce2.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_317_1_Pb1.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_318_1_s2t.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_319_1_vWj.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_3_1_MuN.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_320_1_uDn.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_321_1_tVN.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_32_1_tYN.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_322_1_PNk.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_323_2_jcm.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_324_1_1gf.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_325_1_5MY.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_326_2_7T5.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_327_1_UMy.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_328_1_nWO.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_328_2_Y9z.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_329_2_4ax.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_330_1_IhQ.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_331_1_ouf.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_33_1_Wwv.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_332_1_CGM.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_333_1_Azb.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_334_1_LdP.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_335_1_uCa.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_336_1_AeY.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_337_1_wRX.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_338_1_KtO.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_339_1_0xk.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_339_2_mYM.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_340_1_B5x.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_34_1_01r.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_341_1_AF3.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_341_2_HA6.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_342_1_Zsk.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_343_1_8o1.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_344_1_XlX.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_345_1_aji.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_346_1_MQQ.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_347_1_D77.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_348_1_e88.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_349_1_lGv.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_350_1_hGy.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_350_2_WBY.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_351_1_SpD.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_35_1_8Z6.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_352_1_4Fc.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_353_1_YNm.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_354_1_y1A.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_355_1_Nyz.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_356_1_9VW.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_357_1_OC0.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_357_2_pvR.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_358_1_nJd.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_359_1_O2o.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_360_1_VZ0.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_361_1_8xF.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_36_1_gRQ.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_362_1_dOy.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_363_1_IpZ.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_363_2_ToU.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_364_1_4TD.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_365_1_zOO.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_366_1_bxY.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_367_1_YQG.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_368_2_3n9.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_369_1_bVm.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_370_1_zC7.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_371_1_lfH.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_37_1_8Yn.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_372_2_X9R.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_373_1_HJt.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_374_1_MFy.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_375_1_lKu.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_375_2_UMb.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_376_1_FtU.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_377_1_GBu.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_378_1_HjY.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_379_1_Vad.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_380_1_4hR.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_381_1_jYP.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_381_2_S7u.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_38_1_n1g.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_382_1_sVy.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_383_1_ZVy.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_384_2_4be.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_385_1_UsO.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_386_1_Rq3.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_387_1_2LW.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_388_1_xVW.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_389_1_rR9.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_390_1_0Sv.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_391_1_US9.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_39_1_d0v.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_392_1_AFw.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_393_1_ZX5.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_394_1_qiH.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_395_1_I0B.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_396_1_Jda.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_396_2_wV7.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_397_2_Qi9.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_398_1_P24.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_399_1_5Yc.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_400_1_JT5.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_401_1_22P.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_40_1_6MJ.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_402_1_Hji.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_403_1_YGo.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_404_1_ace.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_405_1_04h.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_406_1_2zm.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_407_1_PCe.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_408_1_8Vf.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_409_1_hMP.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_410_1_YsS.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_411_1_37k.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_412_1_8tg.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_41_2_VI5.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_413_1_OiS.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_414_1_j7c.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_415_1_HfM.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_416_1_xNz.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_417_1_gAJ.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_418_1_6mp.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_419_1_lRQ.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_4_1_iBT.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_420_1_33o.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_42_1_1oM.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_421_1_YvK.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_422_1_q06.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_423_1_2Mk.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_424_1_GTo.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_425_1_AMe.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_425_2_Zma.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_426_1_532.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_427_1_kgM.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_428_1_aBO.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_429_1_EhY.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_430_2_AF0.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_431_1_6KH.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_43_1_Ah7.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_432_2_8n9.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_433_1_PAg.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_434_1_shz.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_435_1_kDv.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_435_2_kaA.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_436_1_TsB.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_437_1_84h.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_438_1_7YD.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_439_1_H9R.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_439_2_jhq.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_440_2_OK3.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_441_1_kva.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_44_1_9ne.root',
]
fnames3 = ['file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_442_1_q1t.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_443_1_n0D.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_444_1_QiW.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_444_2_kIs.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_445_1_OsV.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_446_1_IRr.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_447_1_jnZ.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_448_1_iCX.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_449_2_szx.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_450_1_pP9.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_451_1_b8H.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_45_1_ktH.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_452_1_6mU.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_453_1_dDx.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_454_1_mt6.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_455_1_dVJ.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_455_2_ZTY.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_456_1_K1K.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_457_1_D9b.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_458_1_7mB.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_459_1_sP6.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_460_1_CNt.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_461_1_ixj.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_46_1_ogS.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_462_1_CTo.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_463_1_V6E.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_464_1_Oun.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_465_1_n1K.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_466_1_a4H.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_467_1_7mU.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_468_1_5tp.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_469_1_IyH.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_470_1_FFL.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_471_1_rMF.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_471_2_TrO.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_47_1_ZlT.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_472_2_LWl.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_473_1_FdL.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_474_1_yBl.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_475_1_AFV.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_476_1_q13.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_477_1_iNX.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_478_1_Hsu.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_479_1_6zp.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_479_2_eUf.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_480_1_AF3.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_481_1_Cbh.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_48_1_3Li.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_482_1_Izx.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_483_2_iqB.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_484_1_pex.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_485_1_tPl.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_486_1_3Sd.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_487_1_o2i.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_488_1_GoA.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_489_1_rxU.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_489_2_Wso.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_490_1_ZJ7.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_491_1_TMO.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_49_1_pcR.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_492_1_3I6.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_493_1_Dwz.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_494_1_QEV.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_495_1_WIa.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_496_1_sdW.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_497_1_y2i.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_498_2_XYw.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_499_1_CDA.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_500_1_w4b.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_501_1_ZAl.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_50_1_PZv.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_502_1_Arl.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_503_1_xbp.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_504_1_FxC.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_505_1_yKc.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_505_2_CpP.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_506_1_X1k.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_507_1_M6K.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_508_1_UM6.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_509_1_6an.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_509_2_1rz.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_510_1_I4F.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_511_1_S7l.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_51_1_4iy.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_512_1_OWO.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_513_1_X6x.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_514_1_sWq.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_515_1_eWw.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_516_1_Xbn.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_517_1_YED.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_5_1_76I.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_518_1_qYL.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_519_1_WPF.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_520_1_NkX.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_521_1_DcC.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_52_1_nTa.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_522_1_H39.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_523_1_Pzo.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_524_2_wkB.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_525_1_rn5.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_526_1_ZJn.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_527_1_nif.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_528_3_j4t.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_529_1_waV.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_530_1_TNM.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_531_2_FO0.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_53_1_yFE.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_532_2_M5z.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_533_1_8QM.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_534_1_JL9.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_535_1_gC5.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_535_2_7AK.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_536_1_MPy.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_537_1_1cx.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_538_1_peo.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_539_1_OF6.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_540_1_EHB.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_541_1_xGM.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_54_1_aSH.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_542_1_ZW7.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_543_1_8fb.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_543_2_Qss.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_544_1_vGD.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_545_1_aHz.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_546_1_aHx.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_547_1_CmU.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_548_1_ncb.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_549_1_yKS.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_550_1_XnA.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_551_1_q8P.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_55_1_6Ti.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_552_1_uXQ.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_553_2_7h8.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_554_1_9sJ.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_555_1_PTF.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_556_2_HAI.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_557_1_nkw.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_558_1_UWj.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_559_1_TdK.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_560_1_FYj.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_561_1_WaB.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_56_1_zFR.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_562_1_gb0.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_563_1_DEB.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_564_1_ocG.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_565_1_foW.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_565_2_u8c.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_566_1_2KR.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_567_1_NZM.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_568_1_fDo.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_569_1_eEp.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_570_1_mUn.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_571_1_Yuw.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_57_1_OTQ.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_572_1_Jpd.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_573_1_xFw.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_574_1_fMX.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_575_1_t8k.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_576_1_YJi.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_577_1_7So.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_578_1_dcX.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_579_1_yMW.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_580_1_lgO.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_581_1_h6g.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_58_1_sjf.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_582_1_Lq3.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_583_1_9TJ.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_584_2_Dw6.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_585_1_53i.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_586_1_bDw.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_587_1_xdy.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_588_1_GQ0.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_589_1_KKM.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_590_1_B2B.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_591_1_TAp.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_591_2_NLd.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_59_1_TrG.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_592_1_t7u.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_593_1_1vL.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_594_1_vUR.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_595_1_zEU.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_596_1_Mq2.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_597_1_8NN.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_598_1_zXK.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_599_1_FAY.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_600_1_lZr.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_600_2_uWk.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_601_1_s6O.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_601_2_YLf.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_602_1_jbC.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_60_2_xyH.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_603_1_MeA.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_604_1_ocq.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_604_2_pZS.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_605_1_aVc.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_606_1_wd4.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_607_1_M9l.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_608_1_1Tu.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_609_1_C2I.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_610_1_TlC.root',
]
fnames4 = ['file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_611_1_Z74.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_61_1_uXq.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_612_1_v0w.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_613_1_cXe.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_614_1_QQI.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_615_1_AJ5.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_616_1_FGU.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_617_1_GiC.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_618_1_PCm.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_619_1_Pp9.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_6_1_ray.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_620_1_RFh.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_621_1_sdP.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_62_1_Ny6.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_622_1_pba.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_623_1_RRs.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_624_1_TEX.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_625_1_jlS.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_626_1_gcz.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_627_1_Qim.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_628_1_365.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_629_1_K1J.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_630_1_7Cb.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_631_1_9kZ.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_63_1_DGQ.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_632_1_3XN.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_633_1_BLf.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_634_1_MAd.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_635_1_I8V.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_636_1_Qca.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_637_1_FwE.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_638_1_9vw.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_639_1_fUr.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_640_2_8HB.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_641_1_6ZR.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_642_1_5RH.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_64_2_aiC.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_643_1_fbG.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_644_1_Izv.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_645_1_Cqi.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_646_1_dyD.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_647_1_U2L.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_648_2_gSy.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_649_1_5fa.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_650_1_5s6.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_651_1_Q3T.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_65_1_k5q.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_652_1_h2i.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_653_1_8KW.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_654_1_lKt.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_655_3_e06.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_656_1_DxN.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_657_2_ELr.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_658_1_pVL.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_659_2_qhh.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_660_1_yWL.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_661_1_cKV.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_66_1_cyq.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_662_1_SBH.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_663_1_OfQ.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_664_1_DPx.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_665_1_eek.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_666_1_rxX.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_667_1_BSj.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_668_1_jBa.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_669_1_dYf.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_670_3_LiO.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_671_1_v8O.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_67_1_kvs.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_672_2_mFI.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_673_1_p6J.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_674_1_LhN.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_675_1_xzL.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_676_2_NU4.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_677_1_Iz7.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_678_1_rcK.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_679_1_FYR.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_680_1_J1m.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_681_1_UM6.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_68_1_Mq5.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_682_1_wtq.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_683_1_giR.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_684_1_jUw.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_685_1_Hnv.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_686_2_Kjo.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_687_2_VFn.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_688_1_J2r.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_689_1_9XX.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_690_1_lPq.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_691_1_fRt.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_69_1_eQ2.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_692_1_7EJ.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_693_1_8Ik.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_694_1_aQk.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_695_1_rZr.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_696_2_p0g.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_697_1_XNs.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_698_1_DHD.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_699_2_fnv.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_700_1_Ac8.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_701_2_PG1.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_70_1_4d3.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_702_1_fOV.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_703_2_F1H.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_704_1_4oG.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_705_1_oV1.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_706_1_FOM.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_707_1_Aut.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_708_1_4PQ.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_709_1_jCb.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_710_2_r6X.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_711_1_FLx.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_712_1_S3D.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_71_2_rN4.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_713_1_0o8.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_714_1_be0.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_715_1_QDu.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_716_1_xfG.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_717_1_2it.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_718_1_q2M.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_719_1_qRR.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_7_1_c95.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_720_1_aii.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_721_1_EMs.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_72_1_L7m.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_722_1_31D.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_723_1_oAG.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_724_1_MiR.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_725_2_Kii.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_726_1_BwM.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_727_1_ZJy.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_728_1_QJt.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_729_1_OXK.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_730_2_PXy.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_731_1_xH3.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_73_1_Vnc.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_732_2_Nh0.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_733_1_yJ0.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_734_1_dNC.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_735_1_cZa.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_736_2_QB6.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_737_1_ilT.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_738_1_phf.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_739_1_K9F.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_740_1_A2V.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_741_1_Mjn.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_74_1_sPF.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_742_1_ROq.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_743_1_Myu.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_744_2_wsX.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_745_2_hSH.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_746_1_E2u.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_747_1_XkW.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_748_1_Wsz.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_749_1_5FB.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_750_1_d2d.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_751_1_Q8t.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_75_1_Z3P.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_752_1_aTj.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_753_1_FnU.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_754_1_ISe.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_755_1_Usu.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_756_1_OV3.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_757_1_goH.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_758_1_S8t.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_759_1_svs.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_760_1_bEg.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_761_1_uWX.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_762_1_tOE.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_76_2_Vby.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_763_1_hZE.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_764_1_m8N.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_765_1_oNF.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_766_2_7vJ.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_767_1_AMd.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_768_1_vpj.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_769_1_L6z.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_770_1_Z7k.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_771_1_S89.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_77_1_W4q.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_772_2_gNT.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_773_1_wXW.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_774_2_yM1.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_775_1_ysO.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_776_1_jNV.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_777_1_NrJ.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_778_1_9Kx.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_779_1_Xci.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_780_1_eCh.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_781_1_kWm.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_78_1_ahx.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_782_2_SuV.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_783_1_sJR.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_784_1_Dfl.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_785_2_Bzj.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_786_1_sdW.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_787_1_doB.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_788_2_C5R.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_789_2_RhN.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_790_1_ckk.root',
]
fnames5 = ['file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_791_2_Bf2.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_79_1_uFT.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_792_1_FB2.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_793_1_tY5.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_794_1_PS4.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_795_1_Or4.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_796_1_BPJ.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_797_1_tqz.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_798_1_qmH.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_799_1_bBH.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_800_1_GuY.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_801_1_VSX.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_80_1_mzT.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_802_2_zUG.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_803_1_N9U.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_804_2_lqR.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_805_1_0XO.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_806_1_OKf.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_807_1_JWt.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_808_1_x3A.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_809_1_R2K.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_810_1_jHK.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_811_1_U7O.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_81_1_6GR.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_812_2_KT6.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_813_1_HJF.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_814_1_ns6.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_815_1_aKu.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_816_1_tuK.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_817_1_sPi.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_818_1_C7b.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_819_1_Abh.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_8_1_V73.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_820_1_dRd.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_821_1_Gs8.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_82_1_6dc.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_822_1_cEc.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_823_1_KdY.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_824_2_8tc.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_825_1_oKp.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_826_1_wU3.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_827_2_6Bk.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_828_2_s8F.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_829_1_dWt.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_830_1_RkY.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_831_1_88W.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_83_1_a2w.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_832_1_tKk.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_833_1_7Yb.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_834_1_3jM.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_835_1_ZtV.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_836_1_TU7.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_837_1_2kD.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_838_1_0qe.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_839_1_k3e.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_840_1_Pd1.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_841_2_vSP.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_84_1_WMm.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_842_1_r4l.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_843_1_4Mx.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_844_2_hLb.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_845_1_GJK.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_846_1_QXB.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_847_1_DRv.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_848_1_GSb.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_849_1_PbK.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_850_2_MbE.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_851_1_jS6.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_85_1_lwE.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_852_1_nCx.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_853_2_3m0.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_854_1_hxl.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_855_1_LDJ.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_856_1_rGl.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_857_2_vE5.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_858_1_GCE.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_859_1_UmC.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_860_1_9WV.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_861_1_1j8.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_86_1_eoN.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_862_1_k01.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_863_1_aao.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_864_1_jJ0.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_865_1_pYC.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_866_1_QcT.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_867_1_2t2.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_868_1_rNF.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_869_1_WVN.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_870_1_bKF.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_871_1_LCQ.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_87_1_TT9.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_872_1_xDz.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_873_1_Er5.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_874_1_Ek8.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_875_2_JCo.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_876_1_lYt.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_877_1_Idq.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_878_1_D3e.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_879_1_qiz.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_880_1_kfu.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_881_2_wOB.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_88_1_yCy.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_882_1_sLd.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_883_2_hnZ.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_884_2_Ztm.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_885_1_vVu.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_886_1_zCG.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_887_1_aeu.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_888_1_hd2.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_889_1_Bfx.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_890_1_gaX.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_891_1_iWf.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_89_1_fd9.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_892_2_VwJ.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_893_1_88M.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_894_1_qg9.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_895_1_Mtw.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_896_1_CrO.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_897_1_12D.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_898_2_z85.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_899_1_ej3.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_900_1_DWR.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_901_2_IKU.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_90_1_tiA.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_902_1_Lj1.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_903_1_iTv.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_904_1_mYr.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_905_1_0zu.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_906_1_xY1.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_907_1_w6U.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_908_1_jMD.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_909_1_3o9.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_910_1_9pf.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_911_1_hHy.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_91_1_ukj.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_912_2_qRk.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_913_1_gYR.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_914_1_sy8.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_915_1_kV3.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_916_3_sty.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_917_1_xE5.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_918_1_3l7.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_919_1_FR6.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_9_1_hrB.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_920_1_QkT.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_921_1_lZq.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_92_1_NVz.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_922_2_gsp.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_923_1_Ccp.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_924_1_c5k.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_925_1_FS8.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_926_2_mPI.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_927_1_Iyc.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_928_2_PIM.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_929_1_DYT.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_930_1_IFJ.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_931_1_YEb.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_93_1_X7C.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_932_1_Nz7.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_933_1_Kc4.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_934_1_nQs.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_935_2_927.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_936_1_T6u.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_937_1_IAg.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_938_1_kct.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_939_1_voF.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_940_1_wsv.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_941_1_Oqt.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_94_1_OXf.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_942_1_EEl.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_943_1_JxH.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_944_1_g1C.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_945_1_I2m.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_946_1_4L4.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_947_3_zBW.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_948_1_oi2.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_949_1_nlx.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_950_1_pyR.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_951_1_OOD.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_95_1_lu9.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_952_1_yuP.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_953_1_3Pv.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_954_1_Ofa.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_955_2_2pR.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_956_1_5cI.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_957_1_6rq.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_958_1_Q5y.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_959_2_cte.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_960_2_m4T.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_961_2_3bJ.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_96_1_rB8.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_962_1_gL5.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_963_1_ngl.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_964_1_fl1.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_965_1_PZu.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_966_1_tHe.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_967_1_Bl0.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_968_2_14j.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_969_1_IMW.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_970_1_pHq.root',
]
fnames6 = ['file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_971_1_zvK.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_97_1_Zjf.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_972_1_sbj.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_973_1_JIw.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_974_1_7ZS.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_975_1_LBk.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_976_1_odw.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_977_1_rJe.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_978_1_ryS.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_979_1_tZr.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_980_1_XGo.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_981_1_3cU.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_98_1_rfK.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_982_2_lvX.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_983_2_51v.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_984_1_7Ku.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_985_1_QXa.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_986_1_luM.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_987_1_nj7.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_988_1_FZ5.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_989_1_pbD.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_990_1_y02.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_991_2_Qal.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_992_1_9qe.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_99_2_lNu.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_993_1_2pe.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_994_1_7Bl.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_995_1_VFW.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_996_1_bWj.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_997_2_hTo.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_998_1_xHg.root',
'file:/home/trtomei/hdacs/CMSSW_3_8_7/src/temp/output_999_1_RXc.root',
]

# Input source
process.source = cms.Source("PoolSource",
                            fileNames = cms.untracked.vstring(fnames6)
                            )


# Output definition

process.RECOSIMoutput = cms.OutputModule("PoolOutputModule",
    splitLevel = cms.untracked.int32(0),
    outputCommands = process.RECOSIMEventContent.outputCommands,
    fileName = cms.untracked.string('fnames6.root'),
    dataset = cms.untracked.PSet(
        filterName = cms.untracked.string(''),
        dataTier = cms.untracked.string('GEN-SIM-RECO')
    )
)

# Additional output definition

# Other statements
process.GlobalTag.globaltag = 'MC_38Y_V14::All'

# Path and EndPath definitions
process.raw2digi_step = cms.Path(process.RawToDigi)
process.L1Reco_step = cms.Path(process.L1Reco)
process.reconstruction_step = cms.Path(process.reconstruction)
process.endjob_step = cms.Path(process.endOfProcess)
process.RECOSIMoutput_step = cms.EndPath(process.RECOSIMoutput)

# Schedule definition
process.schedule = cms.Schedule(process.raw2digi_step,process.L1Reco_step,process.reconstruction_step,process.endjob_step,process.RECOSIMoutput_step)

# customisation of the process


# Automatic addition of the customisation functionfrom Configuration.GlobalRuns.reco_TLR_38X

def customiseCommon(process):
    
    #####################################################################################################
    ####
    ####  Top level replaces for handling strange scenarios of early collisions
    ####

    ## TRACKING:
    ## Skip events with HV off
    process.newSeedFromTriplets.ClusterCheckPSet.MaxNumberOfPixelClusters=2000
    process.newSeedFromPairs.ClusterCheckPSet.MaxNumberOfCosmicClusters=20000
    process.secTriplets.ClusterCheckPSet.MaxNumberOfPixelClusters=2000
    process.fifthSeeds.ClusterCheckPSet.MaxNumberOfCosmicClusters = 20000
    process.fourthPLSeeds.ClusterCheckPSet.MaxNumberOfCosmicClusters=20000
    process.thTripletsA.ClusterCheckPSet.MaxNumberOfPixelClusters = 5000
    process.thTripletsB.ClusterCheckPSet.MaxNumberOfPixelClusters = 5000

    ###### FIXES TRIPLETS FOR LARGE BS DISPLACEMENT ######

    ### prevent bias in pixel vertex
    process.pixelVertices.useBeamConstraint = False
    
    ### pixelTracks
    #---- new parameters ----
    process.pixelTracks.RegionFactoryPSet.RegionPSet.nSigmaZ  = 4.06
    process.pixelTracks.RegionFactoryPSet.RegionPSet.originHalfLength = cms.double(40.6)

    ### 0th step of iterative tracking
    #---- new parameters ----
    process.newSeedFromTriplets.RegionFactoryPSet.RegionPSet.nSigmaZ   = cms.double(4.06)  
    process.newSeedFromTriplets.RegionFactoryPSet.RegionPSet.originHalfLength = 40.6

    ### 2nd step of iterative tracking
    #---- new parameters ----
    process.secTriplets.RegionFactoryPSet.RegionPSet.nSigmaZ  = cms.double(4.47)  
    process.secTriplets.RegionFactoryPSet.RegionPSet.originHalfLength = 44.7

    ## ECAL 
    process.ecalRecHit.ChannelStatusToBeExcluded = [ 1, 2, 3, 4, 8, 9, 10, 11, 12, 13, 14, 78, 142 ]

    ###
    ###  end of top level replacements
    ###
    ###############################################################################################

    return (process)


##############################################################################
def customisePPData(process):
    process= customiseCommon(process)

    ## particle flow HF cleaning
    process.particleFlowRecHitHCAL.LongShortFibre_Cut = 30.
    process.particleFlowRecHitHCAL.ApplyPulseDPG = True

    ## HF cleaning for data only
    process.hcalRecAlgos.SeverityLevels[3].RecHitFlags.remove("HFDigiTime")
    process.hcalRecAlgos.SeverityLevels[4].RecHitFlags.append("HFDigiTime")

    ##beam-halo-id for data only
    process.CSCHaloData.ExpectedBX = cms.int32(3)

    ## hcal hit flagging
    process.hfreco.PETstat.flagsToSkip  = 2
    process.hfreco.S8S1stat.flagsToSkip = 18
    process.hfreco.S9S1stat.flagsToSkip = 26
    
    return process


##############################################################################
def customisePPMC(process):
    process=customiseCommon(process)
    
    return process

##############################################################################
def customiseCosmicData(process):

    return process

##############################################################################
def customiseCosmicMC(process):
    
    return process
        

##############################################################################
def customiseExpress(process):
    process= customisePPData(process)

    import RecoVertex.BeamSpotProducer.BeamSpotOnline_cfi
    process.offlineBeamSpot = RecoVertex.BeamSpotProducer.BeamSpotOnline_cfi.onlineBeamSpotProducer.clone()
    
    return process

##############################################################################
def customisePrompt(process):
    process= customisePPData(process)

    import RecoVertex.BeamSpotProducer.BeamSpotOnline_cfi
    process.offlineBeamSpot = RecoVertex.BeamSpotProducer.BeamSpotOnline_cfi.onlineBeamSpotProducer.clone()
    
    return process


process = customisePPMC(process)


# End of customisation functions
