import FWCore.ParameterSet.Config as cms

eventCounterOne = cms.EDAnalyzer("EventCounter")
eventCounterTwo = eventCounterOne.clone()
eventCounterThree = eventCounterOne.clone()
eventCounterFour = eventCounterOne.clone()
eventCounterFive = eventCounterOne.clone()
eventCounterSix = eventCounterOne.clone()
eventCounterSeven = eventCounterOne.clone()
eventCounterEight = eventCounterOne.clone()
eventCounterNine = eventCounterOne.clone()
eventCounterAlpha = eventCounterOne.clone()
eventCounterBeta = eventCounterOne.clone()
eventCounterGamma = eventCounterOne.clone()
eventCounterDelta = eventCounterOne.clone()
eventCounterEpsilon = eventCounterOne.clone()
eventCounterZeta = eventCounterOne.clone()
eventCounterEta = eventCounterOne.clone()
eventCounterTheta = eventCounterOne.clone()
eventCounterIota = eventCounterOne.clone()
